#!/usr/bin/env python3
"""Map SpineNet vertebra detections to axial DICOM slices."""

from __future__ import annotations

import argparse
import ast
import csv
import shutil
from pathlib import Path
from typing import Dict, List, Tuple

import numpy as np
import pandas as pd
import pydicom

TARGET_LEVELS: List[Tuple[str, str, str]] = [
    ("L3-L4","L3","L4"),("L5-S1", "L5", "S1"),("L4-L5", "L4", "L5"),
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Link sagittal SpineNet outputs to axial DICOM slices",
    )
    parser.add_argument(
        "--vertebrae-csv",
        default=r"E:\\segment1\\total-result\\vertebrae.csv",
        help="Path to vertebrae.csv generated by run_sagittal_pipeline.py",
    )
    parser.add_argument(
        "--sagittal-dicom-dir",
        default=r"H:\\MR\\120053171\\aix",
        help="Folder containing sagittal DICOM stack used by SpineNet",
    )
    parser.add_argument(
        "--axial-dicom-dir",
        default=r"H:\\MR\\120053171",
        help="Folder containing axial DICOM slices (all files will be scanned)",
    )
    parser.add_argument(
        "--axial-series",
        default="601",
        help="Only use axial slices whose SeriesNumber matches this value",
    )
    parser.add_argument(
        "--output-csv",
        default=r"E:\\segment1\\total-result\\axial_targets.csv",
        help="Where to save the mapping summary CSV",
    )
    parser.add_argument(
        "--export-dir",
        default=None,
        help="Optional directory to copy the selected axial DICOM slices",
    )
    parser.add_argument(
        "--copy-neighbors",
        action="store_true",
        help="When exporting, also copy +/-1 neighboring slices",
    )
    return parser.parse_args()


def load_sagittal_geometry(folder: Path) -> Dict:
    files = sorted(p for p in folder.glob("*.dcm"))
    if not files:
        raise FileNotFoundError(f"No DICOM files found in {folder}")
    slices = []
    row_dir = col_dir = None
    pixel_spacing = None
    for fp in files:
        ds = pydicom.dcmread(str(fp), stop_before_pixels=True)
        col_dir = np.array(ds.ImageOrientationPatient[:3], dtype=float)
        row_dir = np.array(ds.ImageOrientationPatient[3:], dtype=float)
        pixel_spacing = np.array(ds.PixelSpacing, dtype=float)
        instance = int(getattr(ds, "InstanceNumber", len(slices)))
        origin = np.array(ds.ImagePositionPatient, dtype=float)
        slices.append({"instance": instance, "origin": origin})
    slices.sort(key=lambda item: item["instance"])
    return {
        "slices": slices,
        "row_dir": row_dir,
        "col_dir": col_dir,
        "pixel_spacing": pixel_spacing,
    }


def load_axial_slices(folder: Path, series_number: str) -> List[Dict]:
    slices: List[Dict] = []
    for fp in sorted(folder.glob("*.dcm")):
        try:
            ds = pydicom.dcmread(str(fp), stop_before_pixels=True)
        except Exception:
            continue
        if series_number and str(getattr(ds, "SeriesNumber", "")).strip() != str(series_number):
            continue
        row_dir = np.array(ds.ImageOrientationPatient[:3], dtype=float)
        col_dir = np.array(ds.ImageOrientationPatient[3:], dtype=float)
        normal = np.cross(row_dir, col_dir)
        normal = normal / np.linalg.norm(normal)
        origin = np.array(ds.ImagePositionPatient, dtype=float)
        offset = float(np.dot(normal, origin))
        slices.append(
            {
                "path": fp,
                "instance": int(getattr(ds, "InstanceNumber", len(slices))),
                "origin": origin,
                "normal": normal,
                "offset": offset,
            }
        )
    if not slices:
        raise FileNotFoundError(
            f"No axial DICOM slices with SeriesNumber={series_number} found in {folder}"
        )
    slices.sort(key=lambda item: item["instance"])
    return slices


def parse_polygon(text: str) -> np.ndarray:
    cleaned = text.replace("np.float64", "")
    stripped = cleaned.replace("[", " ").replace("]", " ").replace("\n", " ")
    values = np.fromstring(stripped, sep=" ")
    if values.size % 2 != 0 or values.size == 0:
        raise ValueError(f"Cannot parse polygon from: {text}")
    return values.reshape(-1, 2)


def parse_slice_list(text: str) -> List[int]:
    if not isinstance(text, str):
        return []
    cleaned = text.replace(",", ";").replace("[", "").replace("]", "")
    return [int(tok) for tok in cleaned.split(";") if tok.strip().isdigit()]


def load_vertebrae_centers(csv_path: Path) -> Dict[str, Dict[str, float]]:
    df = pd.read_csv(csv_path)
    df = df[df["predicted_label"].notna()].reset_index(drop=True)
    centers: Dict[str, Dict[str, float]] = {}
    for _, row in df.iterrows():
        label = row["predicted_label"].strip()
        polygon = parse_polygon(row["average_polygon"])
        slice_list = parse_slice_list(str(row["slice_nos"]))
        if not slice_list:
            continue
        center_xy = polygon.mean(axis=0)
        slice_idx = max(0, int(np.median(slice_list)))
        centers[label] = {"center_xy": center_xy, "slice_idx": slice_idx}
    return centers


def pixel_to_world(center_xy: np.ndarray, slice_idx: int, geom: Dict) -> np.ndarray:
    slices = geom["slices"]
    slice_idx = min(max(slice_idx, 0), len(slices) - 1)
    origin = slices[slice_idx]["origin"]
    row_dir = geom["row_dir"]
    col_dir = geom["col_dir"]
    row_spacing, col_spacing = geom["pixel_spacing"]
    y = center_xy[1] * row_spacing
    x = center_xy[0] * col_spacing
    return origin + row_dir * y + col_dir * x


def compute_disc_targets(
    vertebrae: Dict[str, Dict[str, float]],
    geom: Dict,
) -> Dict[str, np.ndarray]:
    targets: Dict[str, np.ndarray] = {}
    for disc_name, upper, lower in TARGET_LEVELS:
        if upper not in vertebrae or lower not in vertebrae:
            continue
        up = pixel_to_world(vertebrae[upper]["center_xy"], vertebrae[upper]["slice_idx"], geom)
        lo = pixel_to_world(vertebrae[lower]["center_xy"], vertebrae[lower]["slice_idx"], geom)
        targets[disc_name] = (up + lo) / 2.0
    return targets


def find_closest_axial_slice(point: np.ndarray, axial_slices: List[Dict]) -> Tuple[int, float]:
    best_idx = -1
    best_dist = float("inf")
    for idx, sl in enumerate(axial_slices):
        dist = abs(np.dot(sl["normal"], point) - sl["offset"])
        if dist < best_dist:
            best_idx = idx
            best_dist = dist
    return best_idx, best_dist


def maybe_copy_slice(dest_dir: Path, level: str, suffix: str, slice_info: Dict) -> Path:
    dest_dir.mkdir(parents=True, exist_ok=True)
    target = dest_dir / f"{level}_{suffix}{slice_info['path'].suffix}"
    shutil.copy2(slice_info["path"], target)
    return target


def main() -> None:
    args = parse_args()
    vertebrae_csv = Path(args.vertebrae_csv)
    sag_dir = Path(args.sagittal_dicom_dir)
    axial_dir = Path(args.axial_dicom_dir)
    out_csv = Path(args.output_csv)
    export_dir = Path(args.export_dir) if args.export_dir else None

    print("Loading sagittal geometry...")
    sag_geom = load_sagittal_geometry(sag_dir)
    print("Parsing vertebrae detections...")
    vertebrae = load_vertebrae_centers(vertebrae_csv)
    print("Computing disc centers...")
    disc_targets = compute_disc_targets(vertebrae, sag_geom)
    if not disc_targets:
        raise RuntimeError("No disc targets could be computed; check vertebrae.csv")

    print("Loading axial slices...")
    axial_slices = load_axial_slices(axial_dir, args.axial_series)

    rows = []
    for level, _, _ in TARGET_LEVELS:
        if level not in disc_targets:
            print(f"Skipping {level}: missing vertebra detections")
            continue
        center = disc_targets[level]
        idx, dist = find_closest_axial_slice(center, axial_slices)
        slice_info = axial_slices[idx]
        entry = {
            "level_name": level,
            "axial_instance": slice_info["instance"],
            "axial_path": str(slice_info["path"]),
            "distance_mm": f"{dist:.3f}",
        }
        if export_dir:
            exported = maybe_copy_slice(export_dir, level, "_center", slice_info)
            entry["exported_center"] = str(exported)
            if args.copy_neighbors:
                for delta, tag in [(-1, "minus1"), (1, "plus1")]:
                    neighbor_idx = idx + delta
                    if 0 <= neighbor_idx < len(axial_slices):
                        neighbor = axial_slices[neighbor_idx]
                        exported_neighbor = maybe_copy_slice(export_dir, level, f"_{tag}", neighbor)
                        entry[f"exported_{tag}"] = str(exported_neighbor)
        rows.append(entry)
        print(f"{level}: axial slice {slice_info['instance']} ({slice_info['path'].name}), distance {dist:.2f} mm")

    if not rows:
        raise RuntimeError("No axial targets were generated")

    print(f"Saving summary to {out_csv}")
    fieldnames = sorted({k for row in rows for k in row.keys()})
    out_csv.parent.mkdir(parents=True, exist_ok=True)
    with out_csv.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    print("Done. Use the exported axial slices (or the CSV mapping) as inputs to LPM.")


if __name__ == "__main__":
    main()
